Update getBroadlinkSharedData.py
Write result as string not bytes. Required for script to run under python3.

Without this change, script will return the following error:
Traceback (most recent call last):
  File "getBroadlinkSharedData.py", line 121, in <module>
    codesFile.write(result.encode('utf-8'))
TypeError: write() argument must be str, not bytes